[2022-08-28 23:47:46,251] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_and_populate_taxigov_datawarehouse.create_dim_rides_table manual__2022-08-28T23:47:41.658303+00:00 [queued]>
[2022-08-28 23:47:46,257] {taskinstance.py:1179} INFO - Dependencies all met for <TaskInstance: create_and_populate_taxigov_datawarehouse.create_dim_rides_table manual__2022-08-28T23:47:41.658303+00:00 [queued]>
[2022-08-28 23:47:46,257] {taskinstance.py:1376} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 23:47:46,257] {taskinstance.py:1377} INFO - Starting attempt 1 of 1
[2022-08-28 23:47:46,257] {taskinstance.py:1378} INFO - 
--------------------------------------------------------------------------------
[2022-08-28 23:47:46,266] {taskinstance.py:1397} INFO - Executing <Task(PostgresOperator): create_dim_rides_table> on 2022-08-28 23:47:41.658303+00:00
[2022-08-28 23:47:46,269] {standard_task_runner.py:52} INFO - Started process 3964 to run task
[2022-08-28 23:47:46,271] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'create_and_populate_taxigov_datawarehouse', 'create_dim_rides_table', 'manual__2022-08-28T23:47:41.658303+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/create_and_populate_taxigov_datawarehouse_dag.py', '--cfg-path', '/tmp/tmpn6tjuvuw', '--error-file', '/tmp/tmp7ubjzx1c']
[2022-08-28 23:47:46,271] {standard_task_runner.py:80} INFO - Job 144: Subtask create_dim_rides_table
[2022-08-28 23:47:46,314] {task_command.py:371} INFO - Running <TaskInstance: create_and_populate_taxigov_datawarehouse.create_dim_rides_table manual__2022-08-28T23:47:41.658303+00:00 [running]> on host ddc8002727e0
[2022-08-28 23:47:46,382] {taskinstance.py:1591} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=create_and_populate_taxigov_datawarehouse
AIRFLOW_CTX_TASK_ID=create_dim_rides_table
AIRFLOW_CTX_EXECUTION_DATE=2022-08-28T23:47:41.658303+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-08-28T23:47:41.658303+00:00
[2022-08-28 23:47:46,392] {base.py:68} INFO - Using connection ID 'redshift_default' for task execution.
[2022-08-28 23:47:47,953] {dbapi.py:231} INFO - Running statement: 
    DROP TABLE IF EXISTS dim_rides;

    CREATE TABLE dim_rides AS ( 
        SELECT
            SHA2(
                qru_corrida,
                256
            ) AS id,
            SHA2(
                CONCAT(
                    CAST(data_abertura AS VARCHAR), 
                    nome_orgao
                ),
                256
            ) AS request_id,
            data_inicio AS started_at,
            data_final AS ended_at,
            origem_latitude AS pickup_latitude,
            origem_longitude AS pickup_longitude,
            destino_efetivo_latitude AS dropoff_latitude,
            destino_efetivo_longitude AS dropoff_longitude,
            km_total AS distance,
            valor_corrida AS cost
        FROM
            raw__taxigov_corridas
    );, parameters: None
[2022-08-28 23:47:59,144] {postgres.py:94} INFO - INFO:  Table "dim_rides" does not exist and will be skipped

[2022-08-28 23:47:59,186] {taskinstance.py:1420} INFO - Marking task as SUCCESS. dag_id=create_and_populate_taxigov_datawarehouse, task_id=create_dim_rides_table, execution_date=20220828T234741, start_date=20220828T234746, end_date=20220828T234759
[2022-08-28 23:47:59,235] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-08-28 23:47:59,271] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
